os: osx

language: cpp

install:
  - mkdir build
  - mkdir bin
  - make

script:
  - bin/apportionment -i data/1940_census_data.csv | diff data/1940_apportionment.csv - 
  - bin/apportionment -i data/1950_census_data.csv | diff data/1950_apportionment.csv - 
  - bin/apportionment -i data/1960_census_data.csv | diff data/1960_apportionment.csv - 
  - bin/apportionment -i data/1970_census_data.csv --state-column state --pop-column pop_total | diff data/1970_apportionment.csv -
  - bin/apportionment -i data/1980_census_data.csv | diff data/1980_apportionment.csv -
  - bin/apportionment -i data/1990_census_data.csv --state-column state --pop-column pop_total | diff data/1990_apportionment.csv -
  - bin/apportionment -i data/2000_census_data.csv --state-column state --pop-column pop_total | diff data/2000_apportionment.csv -
  - bin/apportionment -i data/2010_census_data.csv --state-column state --pop-column pop_total | diff data/2010_apportionment.csv -
  - bin/apportionment -i data/1990_census_data.csv --state-column state --pop-column pop_total --seat-by-seat | python3 compare.py data/1990_priority_values.csv 
  - bin/apportionment -i data/2000_census_data.csv --state-column state --pop-column pop_total --seat-by-seat | python3 compare.py data/2000_priority_values.csv 
  - bin/apportionment -i data/2010_census_data.csv --state-column state --pop-column pop_total --seat-by-seat | python3 compare.py data/2010_priority_values.csv 
