os: osx

language: cpp

script:
  - mkdir build
  - mkdir bin
  - make
  - bin/apportionment -i data/2000_census_data.csv --state-column state --pop-column pop_total | diff data/2000_apportionment.csv -
  - ./bin/apportionment -i data/2010_populations.csv > diff data/2010_apportionment.csv -
